name: adventofcode2021
description: Just having some fun
version: 1.0.0

environment:
  sdk: '>=2.14.2 <3.0.0'


dependencies:
  collection: ^1.15.0
  quantity: ^2.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
